name: chatbot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.3.2
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  remove_markdown: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/openai_logo.jpg
    - assets/images/chat_logo.png
    - assets/images/person.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/educational_chatbot_logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/educational_chatbot_logo.png"
    background_color: "#bbf2ff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/educational_chatbot_logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/educational_chatbot_logo.png"